# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
  armv7: ghcr.io/home-assistant/armv7-base-debian:bookworm
labels:
  org.opencontainers.image.title: "Energy Assistant Add-on"
  org.opencontainers.image.description: "Energy Assistant helps you to control your energy consumption."
  org.opencontainers.image.source: "https://github.com/pail23/energy-assistant-addon"
  org.opencontainers.image.licenses: "MIT"
args:
  TEMPIO_VERSION: "2021.09.0"
  EASS_VERSION: 0.1.1
