# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Energy Assistant
version: "0.1.0"
slug: energy_assistant
description: Energy Assistant helps you to control your energy consumption.
url: "https://github.com/pail23/energy-assistant-addon"
arch:
  - armv7
  - aarch64
  - amd64
init: false
panel_icon: mdi:home-lightning-bolt
panel_admin: false
stage: experimental
ingress: true
ingress_port: 5000
homeassistant_api: true
map:
  - config:rw
image: ghcr.io/pail23/energy-assistant-addon
options:
  config_file: "/config/energy_assistant.yaml"
  log_level: info
schema:
  config_file: str
  log_level: list(debug|info|warning|error)
ports:
  5000/tcp: 5000
